#!/usr/bin/env python3
"""
DB class
"""
def __init__(self) -> None:
    """
    Initialize a new DB instance
    """
    self._engine = create_engine("sqlite:///a.db", echo=True)
    Base.metadata.drop_all(self._engine)
    Base.metadata.create_all(self._engine)
    self.__session = None
    @property
    def _session(self) -> Session:
    """
    Memoized session object
    """
    if self.__session is None:
                                                            DBSession = sessionmaker(bind=self._engine)
                                                                        self.__session = DBSession()
                                                                                return self.__session

                                                                                def add_user(self, email: str, hashed_password: str) -> User:
                                                                                            """
                                                                                                    Adds a new user to the database.

                                                                                                            Args:
                                                                                                                        email (str): User's email address.
                                                                                                                                    hashed_password (str): Hashed password for the user.

                                                                                                                                            Returns:
                                                                                                                                                        User: The newly created User object.
                                                                                                                                                                """
                                                                                                                                                                        new_user = User(email=email, hashed_password=hashed_password)
                                                                                                                                                                                self._session.add(new_user)
                                                                                                                                                                                        self._session.commit()
                                                                                                                                                                                                return new_user

                                                                                                                                                                                                def find_user_by(self, **kwargs) -> User:
                                                                                                                                                                                                            """
                                                                                                                                                                                                                    Finds a user by arbitrary keyword arguments.

                                                                                                                                                                                                                            Args:
                                                                                                                                                                                                                                        **kwargs: Keyword arguments to filter users.

                                                                                                                                                                                                                                                Returns:
                                                                                                                                                                                                                                                            User: The first matching user.

                                                                                                                                                                                                                                                                    Raises:
                                                                                                                                                                                                                                                                                NoResultFound: If no user is found.
                                                                                                                                                                                                                                                                                            InvalidRequestError: If invalid query arguments are passed.
                                                                                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                                                                                            try:
                                                                                                                                                                                                                                                                                                                            return self._session.query(User).filter_by(**kwargs).first()
                                                                                                                                                                                                                                                                                                                                except NoResultFound:
                                                                                                                                                                                                                                                                                                                                                raise NoResultFound("No user found")
                                                                                                                                                                                                                                                                                                                                                    except InvalidRequestError as e:
                                                                                                                                                                                                                                                                                                                                                                    raise InvalidRequestError(f"Invalid query arguments: {e}")

                                                                                                                                                                                                                                                                                                                                                                    def update_user(self, user_id: int, **kwargs) -> None:
                                                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                                                        Updates a user's attributes.

                                                                                                                                                                                                                                                                                                                                                                                                Args:
                                                                                                                                                                                                                                                                                                                                                                                                            user_id (int): ID of the user to update.
                                                                                                                                                                                                                                                                                                                                                                                                                        **kwargs: Keyword arguments with new attribute values.

                                                                                                                                                                                                                                                                                                                                                                                                                                Raises:
                                                                                                                                                                                                                                                                                                                                                                                                                                            ValueError: If an invalid attribute is passed.
                                                                                                                                                                                                                                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                                                                                                                                                                                                                                            user = self.find_user_by(id=user_id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if user is None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    raise ValueError("User not found")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for key, value in kwargs.items():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if hasattr(user, key):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setattr(user, key, value)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            raise ValueError(f"Invalid attribute: {key}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self._session.commit()
